BC: bc/*
feature: feature/*
fix: ['fix/*', 'bug/*', 'bugfix/*']

dependencies: dependencies/*
documentation: ['docs/*', 'documentation/*']
maintenance: maintenance/*
performance: performance/*
refactoring: refactoring/*
'skip changelog': release/*
