BC: bc/*
feature: feature/*
bug: bugfix/*

dependencies: dependencies/*
documentation: ['docs/*', 'documentation/*']
maintenance: maintenance/*
performance: performance/*
refactoring: refactoring/*
'skip changelog': release/*