name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
exclude-labels:
  - 'skip changelog'
categories:
  - title: '⚠️ Breaking Changes'
    labels:
      - 'BC'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐞 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'bugfix'
  - title: '🏎 Performance'
    labels:
      - 'performance'
  - title: '📖 Documentation'
    labels:
      - 'documentation'
  - title: '♻️ Refactoring'
    labels:
      - 'refactoring'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
  - title: '🔧 Maintenance'
    labels:
      - 'maintenance'
version-resolver:
  major:
    labels:
      - 'BC'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'fix'
      - 'bug'
      - 'bugfix'
  default: patch
change-template: '- $TITLE (PR #$NUMBER)'
template: $CHANGES
