image: node:10

pipelines:
    default:
        - step:
            caches:
                - node
            script:
                - npm install --global gscan
                - npm install
                - npm run build
                - npm test
