routes:
  /registrace/: members/signup
  /prihlaseni/: members/signin
  /ucet/: members/account

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: primary_tag:clanky
    data: tag.clanky

taxonomies:
  tag: /tema/{slug}/
  author: /autor/{slug}/
