name: Git Checks

on: [pull_request]

jobs:
  block_merge_with_autosquash_commits:
    runs-on: ubuntu-20.04

    steps:
      - name: Block Merge with Autosquash Commits
        uses: xt0rted/block-autosquash-commits-action@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
